/*
 * generated by Xtext 2.22.0
 */
package edf.tests

import com.google.inject.Inject
import edf.forml0.Model
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.extensions.InjectionExtension
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.jupiter.api.Assertions
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.^extension.ExtendWith
import org.eclipse.xtext.testing.validation.ValidationTestHelper

@ExtendWith(InjectionExtension)
@InjectWith(Forml0InjectorProvider)

class Forml0NegativeParsingTest {
	@Inject
	ParseHelper<Model> parseHelper
	
	@Test
	def void noDeclarationOnly () {
		val result = parseHelper.parse('''
			Boolean b1;
		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(!errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
	}
 	

}

