/*
 * generated by Xtext 2.22.0
 */
package edf.validation

import com.google.inject.Inject
import edf.forml0.AdditionExpression
import edf.forml0.AndExpression
import edf.forml0.BecomesExpression
import edf.forml0.Boolean
import edf.forml0.BooleanFromCtl
import edf.forml0.BooleanLiteral
import edf.forml0.ChangesExpression
import edf.forml0.Clock
import edf.forml0.Ctl
import edf.forml0.DifferenceExpression
import edf.forml0.DivisionExpression
import edf.forml0.DropExpression
import edf.forml0.EqualityExpression
import edf.forml0.Event
import edf.forml0.EventLiteral
import edf.forml0.EveryExpression
import edf.forml0.Expression
import edf.forml0.FirstExpression
import edf.forml0.FollowingExpression
import edf.forml0.FunctionCall
import edf.forml0.GreaterOrEqualExpression
import edf.forml0.GreaterThanExpression
import edf.forml0.IfExpression
import edf.forml0.Integer
import edf.forml0.IntegerDivisionExpression
import edf.forml0.Item
import edf.forml0.LeavesExpression
import edf.forml0.LessOrEqualExpression
import edf.forml0.LessThanExpression
import edf.forml0.MyClock
import edf.forml0.MyRate
import edf.forml0.MyValue
import edf.forml0.NotExpression
import edf.forml0.NumericLiteral
import edf.forml0.OrExpression
import edf.forml0.PowerExpression
import edf.forml0.ProductExpression
import edf.forml0.Property
import edf.forml0.PropertyEvent
import edf.forml0.PropertyPfd
import edf.forml0.PropertyState
import edf.forml0.Real
import edf.forml0.Reference
import edf.forml0.SubstractionExpression
import edf.forml0.Time
import edf.forml0.UnaryMinusExpression
import edf.forml0.WhileExpression
import edf.forml0.WithoutExpression
import edf.forml0.XorExpression
import edf.forml0.inPTime
import edf.forml0.BuiltInFunctionCall
import edf.forml0.AttributeExpression

import static extension org.eclipse.xtext.EcoreUtil2.*
import edf.forml0.Second
import edf.forml0.Tick
import edf.forml0.ClockTime
import edf.forml0.InPClockTime
import edf.forml0.MyDerivative
import edf.forml0.InIntervalExpression

//=============================================================================
//
//	Variability computation for expressions and items
//	 - constant   (only for variables)
//	 - fixed      (only for variables)
//	 - increasing (only for numeric variables)
//	 - decreasing (only for numeric variables)
//	 - normal     (in all other cases)
//
//=============================================================================
interface Forml0Variability {override String toString()}
class constant   implements Forml0Variability {override String toString() {"constant"  }}
class fixed      implements Forml0Variability {override String toString() {"fixed"     }}
class increasing implements Forml0Variability {override String toString() {"increasing"}}
class decreasing implements Forml0Variability {override String toString() {"decreasing"}}
class normal     implements Forml0Variability {override String toString() {"normal"    }}

class Forml0VariabilityProvider {
	// Variability of expressions
	// constant is a subtype of fixed: it is allowed whenever constant is
	public static val constant   = new constant
	public static val fixed      = new fixed
	public static val increasing = new increasing
	public static val decreasing = new decreasing
	public static val normal     = new normal
	
	static val unknown = Forml0ValueProvider::unknown
	
	@Inject extension Forml0ValueProvider
	
	def dispatch Forml0Variability variabilityFor (Expression expr) {
		switch (expr) {
			NumericLiteral:				constant
			Second:						constant
			Time:						increasing
			inPTime:					increasing
			Tick:						constant
			ClockTime:					increasing
			InPClockTime:				increasing
		///	MyDerivative:
		///	MyRate:
			PropertyPfd:				normal
		///	BuiltInFunctionCall:
		
			BooleanLiteral:				constant
			PropertyState:				normal
			BooleanFromCtl:				normal
			
			MyValue:					expr.getContainerOfType(typeof(Item)) ?.variabilityFor ?: normal
			
			EventLiteral:				normal
			PropertyEvent:				normal
			MyClock:					normal
			Clock:						normal
		///	Reference:					
			FunctionCall:				normal
		
		///	AttributeExpression:		
		///	PowerExpression:
		///	UnaryMinusExpression:
			NotExpression:				expr.right ?.variabilityFor ?: normal
			FirstExpression:			normal
			DropExpression:				normal
		///	ProductExpression:
		///	DivisionExpression:
		///	IntegerDivisionExpression:
		///	AdditionExpression
		///	SubstractionExpression:
			WithoutExpression:			normal
			FollowingExpression:		normal
		///	EqualityExpression:	
		///	DifferenceExpression:
		///	LessThanExpression:	
		///	LessOrEqualExpression:
		///	GreaterThanExpression:
		///	GreaterOrEqualExpression:
			InIntervalExpression:		normal
		///	AndExpression:		
			WhileExpression:			normal
		///	OrExpression:				
		///	XorExpression:				
		///	IfExpression
			EveryExpression:			normal
			ChangesExpression:			normal
			BecomesExpression:			normal
			LeavesExpression:			normal
			
			Event:						normal
			Ctl:						normal
		}
	}
 	
	def dispatch Forml0Variability variabilityFor (MyDerivative expr) {
		var container = expr.getContainerOfType(typeof(Real))
		if (container === null) return normal
		if (expr.derivative && (container.variabilityFor == constant || container.variabilityFor == fixed)) return constant 
		if (expr.integral   &&  container.variabilityFor == constant && container.valueFor == 0.0) return constant
		normal 
	}
 	
	def dispatch Forml0Variability variabilityFor (MyRate expr) {
		var container = expr?.getContainerOfType(typeof(Event))
		if (container === null) return normal
		var statements = container.eventDefinition.statements
		if (statements === null) return normal
		var int i
		for (i=0; i < statements.size; i++) {
			var s = statements.get(i)
			if (s.ctl === null && s.rate) return s.rateValue.variabilityFor
		}
		normal
	}
 	
	def dispatch Forml0Variability variabilityFor (Reference expr) {
		var container = expr?.getContainerOfType(typeof(Item))
		if (expr?.identifier?.name === null) normal
		else if (container?.name == expr?.identifier?.name) normal else expr?.identifier?.variabilityFor
	}
 	
	def dispatch Forml0Variability variabilityFor (BuiltInFunctionCall expr) {
		 switch expr.function {
		 	case 'count': 			increasing
		 	case 'duration':    	increasing
		 	case 'clockDuration':   increasing
		 	case 'inPCount': 		increasing
		 	case 'inPDuration':  	increasing
		 	case 'inPClockDuration':increasing
		 	case 'inPMax':			increasing
		 	case 'inPMin':			decreasing
		 	case 'inTMax':			increasing
		 	case 'inTMin':			decreasing
		 	case 'probability': 	normal
		 }
	}
	
	def dispatch Forml0Variability variabilityFor (AttributeExpression expr) {
		var v = expr.atom ?.variabilityFor ?: normal
		if (expr.rate) {
			switch expr.atom {
				EventLiteral:	return normal
				PropertyEvent:	return normal
				default:		return v
			}
		} 
		if (expr.previous) return v
		if (expr.derivative) {if (v == constant || v == fixed)                return constant else return normal}
		if (expr.integral)   {if (v == constant && expr.atom.valueFor == 0.0) return constant else return normal}
		v
	}
 	
	def dispatch Forml0Variability variabilityFor (PowerExpression expr) {
		switch expr.left  ?.variabilityFor ?: normal {
			case expr.left.variabilityFor == constant:	constant
			case expr.left.variabilityFor == fixed:		fixed
			case expr.negative:							normal
			default:	 								expr.left.variabilityFor
		}
	}	
	
	def dispatch Forml0Variability variabilityFor (UnaryMinusExpression expr) {
		switch expr.right ?.variabilityFor ?: normal {
			case constant:		constant
			case fixed:			fixed
			case increasing:	decreasing
			case decreasing:	increasing
			case normal:		normal
		}
	}	
	
	def dispatch Forml0Variability variabilityFor (ProductExpression expr) {
		var leftVar  = expr.left  ?.variabilityFor ?: normal
		var rightVar = expr.right ?.variabilityFor ?: normal
		var leftVal  = expr.left .valueFor
		var rightVal = expr.right.valueFor
		if (leftVar  == constant && leftVal  == 0.0) 	  					  constant   else
		if (rightVar == constant && rightVal == 0.0) 	  					  constant   else
		if (leftVar  == constant && rightVar == constant) 					  constant   else
		if (leftVar  == fixed    && rightVar == constant) 					  fixed      else
		if (leftVar  == constant && rightVar == fixed   ) 					  fixed      else
		if (leftVal  == unknown || rightVal  == unknown) 					  normal     else
		if (leftVar  == constant && leftVal  < 0.0 && rightVar == increasing) decreasing else
		if (leftVar  == constant && leftVal  > 0.0 && rightVar == increasing) increasing else
		if (leftVar  == constant && leftVal  < 0.0 && rightVar == decreasing) increasing else
		if (leftVar  == constant && leftVal  > 0.0 && rightVar == decreasing) decreasing else
		if (rightVar == constant && rightVal < 0.0 && leftVal  == increasing) decreasing else
		if (rightVar == constant && rightVal > 0.0 && leftVal  == increasing) increasing else
		if (rightVar == constant && rightVal < 0.0 && leftVal  == decreasing) increasing else
		if (rightVar == constant && rightVal > 0.0 && leftVal  == decreasing) decreasing else
		normal
	}	
	
	def dispatch Forml0Variability variabilityFor (DivisionExpression expr) {
		var leftVar  = expr.left  ?.variabilityFor ?: normal
		var rightVar = expr.right ?.variabilityFor ?: normal
		var leftVal  = expr.left .valueFor
		var rightVal = expr.right.valueFor
		if (leftVar  == constant && leftVal  == 0.0) 	  					  constant   else
		if (rightVar == constant && rightVal == 0.0) 	  					  normal     else
		if (leftVar  == constant && rightVar == constant) 					  constant   else
		if (leftVar  == fixed    && rightVar == constant) 					  fixed      else
		if (leftVar  == constant && rightVar == fixed   ) 					  fixed      else
		if (leftVal  == unknown || rightVal  == unknown)					  normal     else
		if (leftVar  == constant && leftVal  < 0.0 && rightVar == increasing) decreasing else
		if (leftVar  == constant && leftVal  > 0.0 && rightVar == increasing) increasing else
		if (leftVar  == constant && leftVal  < 0.0 && rightVar == decreasing) increasing else
		if (leftVar  == constant && leftVal  > 0.0 && rightVar == decreasing) decreasing else
		if (rightVar == constant && rightVal < 0.0 && leftVal  == increasing) decreasing else
		if (rightVar == constant && rightVal > 0.0 && leftVal  == increasing) increasing else
		if (rightVar == constant && rightVal < 0.0 && leftVal  == decreasing) increasing else
		if (rightVar == constant && rightVal > 0.0 && leftVal  == decreasing) decreasing else
		normal
	}	
	
	def dispatch Forml0Variability variabilityFor (IntegerDivisionExpression expr) {
		var leftVar  = expr.left  ?.variabilityFor ?: normal
		var rightVar = expr.right ?.variabilityFor ?: normal
		var leftVal  = expr.left .valueFor
		var rightVal = expr.right.valueFor
		if (leftVar  == constant && leftVal  == 0.0) 	  					  constant   else
		if (rightVar == constant && rightVal == 0.0) 	  					  normal     else
		if (leftVar  == constant && rightVar == constant) 					  constant   else
		if (leftVar  == fixed    && rightVar == constant) 					  fixed      else
		if (leftVar  == constant && rightVar == fixed   ) 					  fixed      else
		if (leftVal  == unknown || rightVal  == unknown)					  normal     else
		if (leftVar  == constant && leftVal  < 0.0 && rightVar == increasing) decreasing else
		if (leftVar  == constant && leftVal  > 0.0 && rightVar == increasing) increasing else
		if (leftVar  == constant && leftVal  < 0.0 && rightVar == decreasing) increasing else
		if (leftVar  == constant && leftVal  > 0.0 && rightVar == decreasing) decreasing else
		if (rightVar == constant && rightVal < 0.0 && leftVal  == increasing) decreasing else
		if (rightVar == constant && rightVal > 0.0 && leftVal  == increasing) increasing else
		if (rightVar == constant && rightVal < 0.0 && leftVal  == decreasing) increasing else
		if (rightVar == constant && rightVal > 0.0 && leftVal  == decreasing) decreasing else
		normal
	}	
	
	def dispatch Forml0Variability variabilityFor (AdditionExpression expr) {
		var leftVar  = expr.left  ?.variabilityFor ?: normal
		var rightVar = expr.right ?.variabilityFor ?: normal
		if (leftVar  == constant && rightVar == constant) 					 								 constant   else
		if (leftVar  == fixed    && rightVar == constant) 					 								 fixed      else
		if (leftVar  == constant && rightVar == fixed   ) 					 								 fixed      else
		if (leftVar  == increasing && (rightVar == constant || rightVar == fixed || rightVar == increasing)) increasing else
		if (rightVar == increasing && (leftVar  == constant || leftVar  == fixed || leftVar  == increasing)) increasing else
		if (leftVar  == decreasing && (rightVar == constant || rightVar == fixed || rightVar == decreasing)) decreasing else
		if (rightVar == decreasing && (leftVar  == constant || leftVar  == fixed || leftVar  == decreasing)) decreasing else
		normal
	}	
	
	def dispatch Forml0Variability variabilityFor (SubstractionExpression expr) {
		var leftVar  = expr.left  ?.variabilityFor ?: normal
		var rightVar = expr.right ?.variabilityFor ?: normal
		if (leftVar  == constant && rightVar == constant) 					 								 constant   else
		if (leftVar  == fixed    && rightVar == constant) 					 								 fixed      else
		if (leftVar  == constant && rightVar == fixed   ) 					 								 fixed      else
		if (leftVar  == increasing && (rightVar == constant || rightVar == fixed || rightVar == decreasing)) increasing else
		if (leftVar  == decreasing && (rightVar == constant || rightVar == fixed || rightVar == increasing)) decreasing else
		if (rightVar == increasing && (leftVar  == constant || leftVar  == fixed || leftVar  == decreasing)) decreasing else
		if (rightVar == decreasing && (leftVar  == constant || leftVar  == fixed || leftVar  == increasing)) increasing else
		normal
	}	
	
	def dispatch Forml0Variability variabilityFor (GreaterThanExpression expr) {
		var leftVar  = expr.left  ?.variabilityFor ?: normal
		var rightVar = expr.right ?.variabilityFor ?: normal
		if (leftVar  == constant && rightVar == constant) constant   else
		if (leftVar  == fixed    && rightVar == constant) fixed      else
		if (leftVar  == constant && rightVar == fixed   ) fixed      else
		normal
	}	
	
	def dispatch Forml0Variability variabilityFor (GreaterOrEqualExpression expr) {
		var leftVar  = expr.left  ?.variabilityFor ?: normal
		var rightVar = expr.right ?.variabilityFor ?: normal
		if (leftVar  == constant && rightVar == constant) constant   else
		if (leftVar  == fixed    && rightVar == constant) fixed      else
		if (leftVar  == constant && rightVar == fixed   ) fixed      else
		normal
	}	
	
	def dispatch Forml0Variability variabilityFor (LessOrEqualExpression expr) {
		var leftVar  = expr.left  ?.variabilityFor ?: normal
		var rightVar = expr.right ?.variabilityFor ?: normal
		if (leftVar  == constant && rightVar == constant) constant   else
		if (leftVar  == fixed    && rightVar == constant) fixed      else
		if (leftVar  == constant && rightVar == fixed   ) fixed      else
		normal
	}	
	
	def dispatch Forml0Variability variabilityFor (LessThanExpression expr) {
		var leftVar  = expr.left  ?.variabilityFor ?: normal
		var rightVar = expr.right ?.variabilityFor ?: normal
		if (leftVar  == constant && rightVar == constant) constant   else
		if (leftVar  == fixed    && rightVar == constant) fixed      else
		if (leftVar  == constant && rightVar == fixed   ) fixed      else
		normal
	}	
	
	def dispatch Forml0Variability variabilityFor (EqualityExpression expr) {
		var leftVar  = expr.left  ?.variabilityFor ?: normal
		var rightVar = expr.right ?.variabilityFor ?: normal
		if (leftVar  == constant && rightVar == constant) constant   else
		if (leftVar  == fixed    && rightVar == constant) fixed      else
		if (leftVar  == constant && rightVar == fixed   ) fixed      else
		normal
	}	
	
	def dispatch Forml0Variability variabilityFor (DifferenceExpression expr) {
		var leftVar  = expr.left  ?.variabilityFor ?: normal
		var rightVar = expr.right ?.variabilityFor ?: normal
		if (leftVar  == constant && rightVar == constant) constant   else
		if (leftVar  == fixed    && rightVar == constant) fixed      else
		if (leftVar  == constant && rightVar == fixed   ) fixed      else
		normal
	}	
	
	def dispatch Forml0Variability variabilityFor (AndExpression expr) {
		var leftVar  = expr.left  ?.variabilityFor ?: normal
		var rightVar = expr.right ?.variabilityFor ?: normal
		if (leftVar  == constant && rightVar == constant) constant   else
		if (leftVar  == fixed    && rightVar == constant) fixed      else
		if (leftVar  == constant && rightVar == fixed   ) fixed      else
		normal
	}	
	
	def dispatch Forml0Variability variabilityFor (OrExpression expr) {
		var leftVar  = expr.left  ?.variabilityFor ?: normal
		var rightVar = expr.right ?.variabilityFor ?: normal
		if (leftVar  == constant && rightVar == constant) constant   else
		if (leftVar  == fixed    && rightVar == constant) fixed      else
		if (leftVar  == constant && rightVar == fixed   ) fixed      else
		normal
	}	
	
	def dispatch Forml0Variability variabilityFor (XorExpression expr) {
		var leftVar  = expr.left  ?.variabilityFor ?: normal
		var rightVar = expr.right ?.variabilityFor ?: normal
		if (leftVar  == constant && rightVar == constant) constant   else
		if (leftVar  == fixed    && rightVar == constant) fixed      else
		if (leftVar  == constant && rightVar == fixed   ) fixed      else
		normal
	}	
	
	def dispatch Forml0Variability variabilityFor (IfExpression expr) {
		var condVar = expr.condition.expression ?.variabilityFor ?: normal
		var thenVar = expr.then      ?.variabilityFor ?: normal
		var elseVar = expr.^else     ?.variabilityFor ?: normal
		if (condVar == constant && thenVar == constant && elseVar == constant) return constant
		if (condVar == fixed    
			&& (thenVar == constant || thenVar == fixed) 
			&& (elseVar == constant || elseVar == fixed)
		) return fixed 
		normal
	}	
	
	def dispatch Forml0Variability variabilityFor (Item item) {
		switch item {
			Event:		normal
			Property:	normal
			Ctl:		normal
		}
	}
	
	def dispatch Forml0Variability variabilityFor (Boolean item) {
		if (item.constant)																  return constant
		if (item.fixed) 																  return fixed
		if (item.booleanDefinition.global && item.booleanDefinition.external)			  return normal
		if (item.booleanDefinition.global && item.booleanDefinition.globalValue !== null) return item.booleanDefinition.globalValue.expression ?.variabilityFor ?: normal
		normal
	}
	
	def dispatch Forml0Variability variabilityFor (Integer item) {
		if (item.constant)																  return constant
		if (item.fixed)  																  return fixed
		if (item.integerDefinition.global && item.integerDefinition.external) 			  return normal
		if (item.integerDefinition.global && item.integerDefinition.globalValue !== null) return item.integerDefinition.globalValue.expression ?.variabilityFor ?: normal
		normal
	}
	
	def dispatch Forml0Variability variabilityFor (Real item) {
		if (item.constant) 															return constant
		if (item.fixed)    															return fixed
		if (item.realDefinition.global && item.realDefinition.external) 			return normal
		if (item.realDefinition.global && item.realDefinition.globalValue !== null) return item.realDefinition.globalValue.expression ?.variabilityFor ?: normal
		normal
	}
}	
